server:
  port: 8080

eureka:
  client:
    fetch-registry: true  #Se coloca true por que es cliente
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:  # Aqui se configura los apis gateway
          - id: usuario-service
            uri: lb://usuario-service   # lb hace referencia a balanceo de carga
            predicates:
              - Path=/usuario/**
          - id: carro-service
            uri: lb://carro-service   # lb hace referencia a balanceo de carga
            predicates:
              - Path=/carro/**
          - id: moto-service
            uri: lb://moto-service   # lb hace referencia a balanceo de carga
            predicates:
              - Path=/moto/**