spring:
  application:
    name: moto-service

server:
  port: 8083
eureka:
  client:
    fetch-registry: true  #Se coloca true por que es cliente
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost